/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UIObject;

import database.DAO_BanBe;
import entity.BanBe;
import entity.TaiKhoan;
import event.PublicEvent;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author ADMIN
 */
public class FriendSearchCard extends javax.swing.JPanel {

    /**
     * Creates new form friendCard
     */
    private TaiKhoan user;
    private boolean clicked = false;
    
    public FriendSearchCard(TaiKhoan user) {
        initComponents();
        this.user = user;
        lblUsername.setText(user.getUsername());
        btnAddFriend.setText("Kết bạn");
    }
    
    public void setStatus(){
          if(user.getTrangThai() == 1){
            lblStatus.setText("Active now");
            lblStatus.setForeground(new java.awt.Color(40, 147, 59));
        }else{
             lblStatus.setText("Offline");
             lblStatus.setForeground(new Color(160, 160, 160));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUsername = new javax.swing.JLabel();
        btnAddFriend = new javax.swing.JButton();
        lblStatus = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));

        lblUsername.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblUsername.setText("Username");

        btnAddFriend.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAddFriend.setText("Kết bạn");
        btnAddFriend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddFriendActionPerformed(evt);
            }
        });

        lblStatus.setForeground(new java.awt.Color(0, 204, 0));
        lblStatus.setText("active");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(84, 84, 84)
                .addComponent(btnAddFriend, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblUsername)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblStatus))
                    .addComponent(btnAddFriend, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))
                .addContainerGap(12, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddFriendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddFriendActionPerformed
        if (!clicked) {
            clicked = true;
            btnAddFriend.setText("Hủy");
            PublicEvent.getInstance().getEventFriend().addFriend(this.user.getUsername());
        }
        else {
            clicked = false;
            btnAddFriend.setText("Kết bạn");
            PublicEvent.getInstance().getEventFriend().unfriend(new BanBe("", this.user.getUsername(), null));
        }
        
    }//GEN-LAST:event_btnAddFriendActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddFriend;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblUsername;
    // End of variables declaration//GEN-END:variables
}
