/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package main_ui;

import UIObject.ChatCard;
import UIObject.GroupCard;
import entity.NhomChat;
import entity.TaiKhoan;
import event.EventChatList;
import event.EventGroupChatList;
import event.PublicEvent;
import java.awt.Component;
import java.util.List;
import javax.swing.JPanel;
import net.miginfocom.swing.MigLayout;
import swing.ModifiedScrollBar;
import java.util.ArrayList;

/**
 *
 * @author ADMIN
 */
public class ChatListAndSearch extends javax.swing.JPanel {

    private ArrayList<TaiKhoan> userAccounts;
    
    
    public ChatListAndSearch() {
        initComponents();
        init();
        sp.setVerticalScrollBar(new ModifiedScrollBar());
        sp.setHorizontalScrollBar(new ModifiedScrollBar());
        chatListPanel.setLayout(new MigLayout("wrap"));
        
        initEvent();
        
    }
    
    public void refreshChatListPanel(){
        chatListPanel.repaint();
        chatListPanel.revalidate();
    }
    
    public void init(){
        userAccounts = new ArrayList<>();
    }
    
    public JPanel getChatListPanel(){
        return this.chatListPanel;
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sp = new javax.swing.JScrollPane();
        chatListPanel = new javax.swing.JPanel();
        txtUsernamSearch = new javax.swing.JTextField();
        searchButtonChat = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 255));

        javax.swing.GroupLayout chatListPanelLayout = new javax.swing.GroupLayout(chatListPanel);
        chatListPanel.setLayout(chatListPanelLayout);
        chatListPanelLayout.setHorizontalGroup(
            chatListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 232, Short.MAX_VALUE)
        );
        chatListPanelLayout.setVerticalGroup(
            chatListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 738, Short.MAX_VALUE)
        );

        sp.setViewportView(chatListPanel);

        txtUsernamSearch.setToolTipText("Nhập tên");

        searchButtonChat.setText("Tìm kiếm");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtUsernamSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchButtonChat)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(sp, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUsernamSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchButtonChat))
                .addGap(4, 4, 4)
                .addComponent(sp, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel chatListPanel;
    private javax.swing.JButton searchButtonChat;
    private javax.swing.JScrollPane sp;
    private javax.swing.JTextField txtUsernamSearch;
    // End of variables declaration//GEN-END:variables

    private void initEvent() {
        PublicEvent.getInstance().addEventChatList(new EventChatList(){
            @Override
            public void newUser(List<TaiKhoan> users) {
                for (TaiKhoan user : users) {
                    userAccounts.add(user);
                    chatListPanel.add(new ChatCard(user), "wrap");
                    refreshChatListPanel();
                }  
            }

            @Override
            public void userConnect(TaiKhoan user) {
               for(TaiKhoan u : userAccounts) {
                    if (u.getUsername().equals(u.getUsername())) {
                        u.setTrangThai(1);
                        PublicEvent.getInstance().getEventChat().updateUser(user);
                        break;
                    }
                }
               
               userAccounts.forEach(item ->{
                    System.out.println(item);
                });  
               for(int i=0;i<userAccounts.size();i++){
                    ChatCard c = (ChatCard) chatListPanel.getComponent(i);
                    System.out.println(c.getUser());
                    if(c.getUser().getUsername().equals(user.getUsername())){
                        c.getUser().setTrangThai(1);
                        c.setStatus();
                    }
                }
            }

            @Override
            public void userDisconnect(TaiKhoan user) {
                for(TaiKhoan u : userAccounts) {
                    if (u.getUsername().equals(u.getUsername())) {
                        u.setTrangThai(0);
                        PublicEvent.getInstance().getEventChat().updateUser(user);
                        break;
                    }
                }
               for(int i=0;i<userAccounts.size();i++){
                    ChatCard c = (ChatCard) chatListPanel.getComponent(i);
                    if(c.getUser().getUsername().equals(user.getUsername())){
                        c.getUser().setTrangThai(1);
                        c.setStatus();
                    }
                }
            }            
        });
    }
}
