/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package main_ui;

import entity.NhomChat;
import forSubmitOnly.*;
import entity.TaiKhoan;
import event.PublicEvent;
import java.awt.Color;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;

/**
 *
 * @author ADMIN
 */
public class GroupChatTitle extends javax.swing.JPanel {

    /**
     * Creates new form ChatTitle
     */
    private TaiKhoan user;
    private NhomChat group;
    public GroupChatTitle() {
        initComponents();
    }

    public void setUser(TaiKhoan user){
        this.user = user;
    }
    
    public void setGroupName(NhomChat group){
        this.group = group;
        lbName.setText(group.getTenNhom());
    }
    
    public void updateGroup(NhomChat group){
        if(this.group == group){
            setGroupName(group);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        layer = new javax.swing.JLayeredPane();
        layerSearch = new javax.swing.JLayeredPane();
        searchB = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        lbName = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 5, 0, new java.awt.Color(51, 51, 51)));

        layer.setLayout(new java.awt.BorderLayout());

        layerSearch.setLayout(new javax.swing.BoxLayout(layerSearch, javax.swing.BoxLayout.LINE_AXIS));

        searchB.setToolTipText("Nhập tin nhắn");
        searchB.setPreferredSize(new java.awt.Dimension(50, 26));
        layerSearch.add(searchB);

        searchButton.setText("Tìm kiếm");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });
        layerSearch.add(searchButton);

        lbName.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        lbName.setForeground(new java.awt.Color(66, 66, 66));
        lbName.setText("group1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                        .addComponent(layerSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(layer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(layer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(layerSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbName))
                .addGap(11, 11, 11))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        var text = new String(searchB.getText().getBytes(StandardCharsets.UTF_8), StandardCharsets.UTF_8);
        if (text.strip().isEmpty()) {
            return;
        }
        var query = text.strip().split("\\s+");
        var s = new ArrayList<String>();
        for (var word : query) {
            s.add("noidung like N'%" + word + "%'");
        }
        text = "where " + String.join(" or ", s);
        PublicEvent.getInstance().getEventChat().searchFromAUser(new TaiKhoan(group.getIDNhom(), "", ""), text);
    }//GEN-LAST:event_searchButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane layer;
    private javax.swing.JLayeredPane layerSearch;
    private javax.swing.JLabel lbName;
    private javax.swing.JTextField searchB;
    private javax.swing.JButton searchButton;
    // End of variables declaration//GEN-END:variables
}
