/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package main_ui;

import UIObject.GroupCard;
import entity.BanBe;
import entity.NhomChat;
import entity.ThanhVienNhomChat;
import event.EventGroupChatList;
import event.PublicEvent;
import java.util.ArrayList;
import javax.swing.JPanel;
import net.miginfocom.swing.MigLayout;
import swing.ModifiedScrollBar;

/**
 *
 * @author ADMIN
 */
public class GroupChatListAndSearch extends javax.swing.JPanel {

    private ArrayList<NhomChat> groupList;
    private ArrayList<BanBe> friends;

    public GroupChatListAndSearch() {
        initComponents();
        groupChatListPanel.setLayout(new MigLayout("wrap"));
        sp.setVerticalScrollBar(new ModifiedScrollBar());
        sp.setHorizontalScrollBar(new ModifiedScrollBar());
        initEvent();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sp = new javax.swing.JScrollPane();
        groupChatListPanel = new javax.swing.JPanel();
        txtUsernamSearch = new javax.swing.JTextField();
        searchButtonChat = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 255));

        javax.swing.GroupLayout groupChatListPanelLayout = new javax.swing.GroupLayout(groupChatListPanel);
        groupChatListPanel.setLayout(groupChatListPanelLayout);
        groupChatListPanelLayout.setHorizontalGroup(
            groupChatListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 388, Short.MAX_VALUE)
        );
        groupChatListPanelLayout.setVerticalGroup(
            groupChatListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 738, Short.MAX_VALUE)
        );

        sp.setViewportView(groupChatListPanel);

        txtUsernamSearch.setToolTipText("Nhập tên");

        searchButtonChat.setText("Tìm kiếm");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtUsernamSearch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchButtonChat)
                .addContainerGap())
            .addComponent(sp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUsernamSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchButtonChat))
                .addGap(4, 4, 4)
                .addComponent(sp, javax.swing.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void init() {
        groupList = new ArrayList<>();
    }

    private void initEvent() {
        PublicEvent.getInstance().addEventGroupChatList(new EventGroupChatList() {
            @Override
            public void setData(ArrayList<NhomChat> groups, ArrayList<Boolean> roles) {
                groupList.clear();
                groupChatListPanel.removeAll();
                for (int i = 0; i < groups.size(); i++) {
                    groupList.add(groups.get(i));
                    groupChatListPanel.add(new GroupCard(groups.get(i), roles.get(i)), "wrap");
                    refreshGroupChatListPanel();
                }
                for (int i = 0; i < groupList.size(); i++) {
                    var groupCard = (GroupCard) groupChatListPanel.getComponent(i);
                    groupCard.setFriendList(friends);
                }
                System.out.println(groupList);
            }

            @Override
            public void newGroup(NhomChat group, boolean role) {
                groupList.add(group);
                groupChatListPanel.add(new GroupCard(group, role), "wrap");
                refreshGroupChatListPanel();
            }

            @Override
            public void setMember(ArrayList<ThanhVienNhomChat> members) {
                for (int i = 0; i < groupList.size(); i++) {
                    var groupCard = (GroupCard) groupChatListPanel.getComponent(i);
                    System.out.println("setMem " + groupCard.getGroup());
                    System.out.println("List group " + groupList);
                    System.out.println("Mmebers " + members);
                    if (groupCard.getGroup().getIDNhom().equals(members.get(0).getIDNhom())) {
                        groupCard.setMemberList(members);
                        return;
                    }
                }
            }
        });
    }

    public void setFriend(ArrayList<BanBe> friends) {
        this.friends = friends;
    }

    public JPanel getGroupChatListPanel() {
        return this.groupChatListPanel;
    }

    public ArrayList<NhomChat> getGroup() {
        return this.groupList;
    }

    private void refreshGroupChatListPanel() {
        groupChatListPanel.repaint();
        groupChatListPanel.revalidate();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel groupChatListPanel;
    private javax.swing.JButton searchButtonChat;
    private javax.swing.JScrollPane sp;
    private javax.swing.JTextField txtUsernamSearch;
    // End of variables declaration//GEN-END:variables
}
